# Generated by Django 5.1.7 on 2025-03-18 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(default='guest', max_length=100)),
                ('task_difficulty', models.FloatField()),
                ('error_rate', models.FloatField()),
                ('response_time', models.FloatField()),
                ('rl_decision', models.CharField(max_length=50)),
                ('model_confidence', models.FloatField(default=1.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
